### ISSUE TITLE
n00bs manual to get started and included in ISO for offline use.

### ISSUE THREAD

**Issue by 3rdwiki** [linuxlite/liteprojects2.0#1]
Hi there I saw you on bountysource, and I thought I'd highlight an issue for offline users.

Well, a proper manual of how to use the command line etc would be very beneficial.
Coupled with this is the linux eco-system with how to install linux programs from github etc.
(from the command line) - and where to move the install to keep your Dloads folder free etc.

Secondly, a couple of instances ago I saw a video of how to download the various programs using an
install scripts ... a good idea - but how about how to use the various programs ?

There are multiple manuals that can be used to map out the likes of the gimp etc - So that people have a walk-through of how to get basic instances of cut and paste, for example, to do their work.

I think this is the real intelligence of linux lite - a system that allows users to explore the system of occasionally going to the coffee shop and installing programs - and then spending the week looking at the off-line documentation that accompanies Linux Lite.

So tell me what you think ? It's a long term project that could be done on a wiki but for offline use.

My $15 dollars to that !

PS Could you add the bounty-tracker to bountysource so that I can back this offline issue ?

**Comment by linuxlite** [comment]
The installed Help Manual is offline

**Comment by 3rdwiki** [comment]
Oh yeah, sorry I got it.
https://github.com/3rdwiki/litemanual

Cheers for the swift response.

**Comment by linuxlite** [comment]
Your welcome.
